name = "XKCD Fabric Server"
author = "Michael"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc083ae8a29b278d597304817c2143c9da466a7a316acc80fe182286afc48b13"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
