name = "XKCD Fabric Server"
author = "Michael"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a44c221b4c78b532009b4dd611ddf23942178b56101fb0eddc08e8d71ab33b5"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
