name = "XKCD Fabric Server"
author = "Michael"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9d7cb939eaabf6e1979f37c2058a18b6f072d79ce2fc6493f1ca39471e18029"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
