version: "3.8"

services:
  memos:
    image: neosmemo/memos:${MEMOS_VERSION}
    container_name: memos
    restart: unless-stopped
    ports:
      - "5230:5230"
    volumes:
      - ${APPDATA_PATH:}/memos:/var/opt/memos
    environment:
      TZ: America/Los_Angeles
      MEMOS_MODE: prod
      MEMOS_ADDR: 0.0.0.0
      MEMOS_PORT: 5230
      MEMOS_DATA: /var/opt/memos
      # MEMOS_INSTANCE_URL: "https://memos.yourdomain.com"
    labels:
      net.unraid.docker.webui: "http://[IP]:[PORT:5230]"
      net.unraid.docker.icon: "https://raw.githubusercontent.com/usememos/memos/main/web/static/logo.png"